### ISSUE TITLE
Tracker for checkboxes

### ISSUE THREAD

**Issue by ameresv** [pyrochlore/obsidian-tracker#252]
Hi! 
According to the [documentation provided](https://github.com/pyrochlore/obsidian-tracker/blob/master/docs/TargetEvaluation.md), there are eight types of searchTypes: tag, frontmatter, wiki, text, table, dvField, task, and fileMeta. So, which I should use to search for checkbox properties? 
If I am not mistaken, has [this post ](https://forum.obsidian.md/t/how-to-search-checkmark-checkbox-properties/67387) anything that could help me?
Thanks in advance
Regards

**Comment by lazyguru** [comment]
#177 fixes this. However, the owner of this repo has been MIA for a while. I have merged most of the open PRs here on my fork (including that fix). I've tried reaching out to @pyrochlore to attempt to take it over (or get their blessing in using my fork as the pointer for future releases). If I don't hear back from them soon I plan to open a request to try to have the plugin changed to point at my repo instead so that the plugin can continue to be maintained by the community. You can install my current release either manually or using BRAT. See my the latest release here: https://github.com/lazyguru/obsidian-tracker/releases/latest

**Comment by aebenson** [comment]
@lazyguru About a month ago, I started the process to get a new plugin registered with obsidian (Tracker+). The version that will be published--assuming they approve it--includes changes from 3 of the open PRs here, including:

- support for inline dataview fields
- aspect ratio
- booleans in Frontmatter

https://github.com/greater-than/Obsidian-Tracker-Plus
https://github.com/obsidianmd/obsidian-releases/pull/2497

I'm working on a refactor that should make unit testing easier, and I hope to have those changes merged this week. 

I would love to have other contributors help keep things moving forward.

**Comment by lazyguru** [comment]
@aebenson I would suggest making a PR here. I've been in contact with @pyrochlore and I expect this repo will become active again in the very near future.

**Comment by aebenson** [comment]
Thanks for the info @lazyguru 

It would be great if @pyrochlore would jump back in here and give us an update--and if they have any plans to add additional code owners so we can keep this project moving forward. I'm going to keep on with the refactor. If/when we get an update I can create a PR for this repo.

**Comment by greater-than** [comment]
Tracker+ is now available as a community plugin. It includes these updates.

> * support for inline dataview fields
> * aspect ratio
> * booleans in Frontmatter
> 
> https://github.com/greater-than/Obsidian-Tracker-Plus [obsidianmd/obsidian-releases#2497](https://github.com/obsidianmd/obsidian-releases/pull/2497)

 If pyrochlore ever resurfaces, we can figure out how to combine our efforts.

**Comment by lazyguru** [comment]
Hey all, I now have write access here and will be merging PRs and getting releases out within the next few days

**Comment by aebenson** [comment]
@lazyguru let's find a way to connect on this. Folks have already downloaded Tracker+, and I've done a bunch of work to (hopefully) be able to make testing easier--unit tests first, then some integration/e2e

**Comment by aebenson** [comment]
I'm fine creating a PR here, but it's going to look pretty nasty since every file has changed. Let me know what you think

**Comment by lazyguru** [comment]
Let me get the other PRs merged, but it would be good to see what you have as a PR against this repo. @pyrochlore told me they still use this plugin themselves and may want to contribute code to it again in the future (they've just been too busy with work to keep it up)

**Comment by aebenson** [comment]
Sounds good. Before I go through the effort, would you mind taking a quick look at the code in my repo to get a sense of what's incoming? Any comments/feedback would be greatly appreciated. It won't be as simple as merging back to the forked repo and then creating PR since a bunch of copy will need to be revised.

**Comment by lazyguru** [comment]
Yes, I can do that. I will look at it some time this week.

**Comment by lazyguru** [comment]
@aebenson let's move this discussion to a new issue as I just released 1.11.0 that fixes the initially reported issue here.

@ameresv please update to 1.11.0 as it adds support for checkboxes
