### ISSUE TITLE
I had the wish to track words...

### ISSUE THREAD

**Issue by Doom666** [pyrochlore/obsidian-tracker#27]
this way I can make a dashboard with word streaks, daily words in my could and on given projects see my writing progress over time, and of course, be a bit ashamed of myself when I slack off.
many statistics I can think about like most words written ever. accumulative words in the vault, count streaks, and words to go to a given goal....

**Comment by pyrochlore** [comment]
These can be done easily under current structure
1. Words Count over dates
2. Statistics (e.g. max/min/Average count over dates)
3. Count streak over dates

Others like writing progress over time, most words written ever, accumulative works
needs more consideration.

**Comment by pyrochlore** [comment]
>    1. Words Count over dates
>    2. Statistics (e.g. max/min/Average count over dates)
>    3. Count streak over dates

Now these three can be done with the new released version 1.6.1.
[Here](https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/TestWordCounting.md) is the example.

**Comment by pyrochlore** [comment]
After considering the issue, 
I decided not to add the function like 'writing progress over time' or 'most words written ever',
since they are very much different from the purpose of this plugin, tracking occurrences and numbers of 'given' targets.

They could be implemented in a separated plugin by someone or if I have time some day. :P

**Comment by pyrochlore** [comment]
Parts of the features were implemented.
I will close the issue here.
